name: run-existing-test
env:
  apiKey: "a7b501806ee7a488aca875b6"
  apiSecret: "9ffb0450e3865f183cf553fdb49c3f94f6aae0a97b2d741170211b566284d877a7150f38"
  testID: "6973567"
  continuePipeline: "false"
  showTailLog: "false"
  
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: BlazeRunner-BZR/Github-Action@v8.1
        id: run-test
        with:
          apiKey: ${{env.apiKey}}
          apiSecret: ${{env.apiSecret}}
          testID: ${{env.testID}}
          uploadFileCheck: ${{env.uploadFileCheck}}
          inputStartFile: ${{env.inputStartFile}}
          continuePipeline: ${{env.continuePipeline}}
          showTailLog: ${{env.showTailLog}}
